spring.datasource.url=jdbc::postgresql://autoresdb_n6rx_user:Zubyk8aOmhzIufdss0FbgDCJsDf4xHu8@dpg-d4g9cpe3jp1c73dggn10-a.oregon-postgres.render.com/autoresdb_n6rx
spring.datasource.username=autoresdb_n6rx_user
spring.datasource.password=Zubyk8aOmhzIufdss0FbgDCJsDf4xHu8

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.platform=postgres
